### ISSUE TITLE
Error `java.lang.NullPointerException`

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mnconvert#168]
Source issue: https://github.com/metanorma/mnconvert/issues/162

Error occurs when set the parameter `--output`:
`... wrappedform.xml --output wrappedconverted.xml --output-format xml`

On Windows:
```
Transforming...
java.lang.NullPointerException
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:98)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at org.metanorma.STS2MN_XsltConverter.convertsts2mn(STS2MN_XsltConverter.java:223)
	at org.metanorma.STS2MN_XsltConverter.process(STS2MN_XsltConverter.java:134)
	at org.metanorma.mnconvert.main(mnconvert.java:396)
```

On Ubuntu:
```
Transforming...
java.lang.NullPointerException
        at java.base/sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:75)
        at java.base/sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
        at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at org.metanorma.STS2MN_XsltConverter.convertsts2mn(STS2MN_XsltConverter.java:223)
        at org.metanorma.STS2MN_XsltConverter.process(STS2MN_XsltConverter.java:134)
        at org.metanorma.mnconvert.main(mnconvert.java:396)
```

**Comment by Intelligent2013** [comment]
It's working ok, then `--output` sets to relative
`--output .\wrappedconverted.xml`
or absolute path:
`--output D:\Interchange\wrappedconverted.xml`

**Comment by Intelligent2013** [comment]
Fixed.
