### ISSUE TITLE
Windows build issue: NoMethodError: undefined method `full_name' for nil:NilClass

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mnconvert#269]
From https://github.com/metanorma/mnconvert/actions/runs/3191943380/jobs/5208847647:
```
Fetching nokogiri 1.13.8
Installing nokogiri 1.13.8 with native extensions
--- ERROR REPORT TEMPLATE -------------------------------------------------------


NoMethodError: undefined method `full_name' for nil:NilClass
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/installer/parallel_installer.rb:124:in `block (2 levels) in check_for_unmet_dependencies'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/installer/parallel_installer.rb:123:in `each'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/installer/parallel_installer.rb:123:in `block in check_for_unmet_dependencies'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/installer/parallel_installer.rb:122:in `each'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/installer/parallel_installer.rb:122:in `check_for_unmet_dependencies'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/installer/parallel_installer.rb:100:in `call'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/installer/parallel_installer.rb:71:in `call'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/installer.rb:254:in `install_in_parallel'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/installer.rb:209:in `install'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/installer.rb:89:in `block in run'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/process_lock.rb:12:in `block in lock'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/process_lock.rb:9:in `open'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/process_lock.rb:9:in `lock'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/installer.rb:71:in `run'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/installer.rb:23:in `install'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/cli/install.rb:62:in `run'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/cli.rb:257:in `block in install'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/settings.rb:131:in `temporary'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/cli.rb:256:in `install'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/cli.rb:31:in `dispatch'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/cli.rb:25:in `start'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/exe/bundle:48:in `block in <top (required)>'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/exe/bundle:36:in `<top (required)>'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/bin/bundle:23:in `load'
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/bin/bundle:23:in `<main>'



## Environment


Bundler       2.3.23
  Platforms   ruby, x64-mingw32
Ruby          2.7.6p219 (2022-04-12 revision c9c2245c0a251[76](https://github.com/metanorma/mnconvert/actions/runs/3191943380/jobs/5208847647#step:16:77)072e02db9254f0e0c84c[80](https://github.com/metanorma/mnconvert/actions/runs/3191943380/jobs/5208847647#step:16:81)5cd) [x64-mingw32]
  Full Path   C:/hostedtoolcache/windows/Ruby/2.7.6/x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      3.1.6
  Gem Home    C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0
  Gem Path    C:/Users/runneradmin/.gem/ruby/2.7.0;C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0
  User Home   C:/Users/runneradmin
  User Path   C:/Users/runneradmin/.gem/ruby/2.7.0
  Bin Dir     C:/hostedtoolcache/windows/Ruby/2.7.6/x64/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1n  15 Mar 2022
  Loaded      OpenSSL 1.1.1n  15 Mar 2022
  Cert File   C:/hostedtoolcache/windows/Ruby/2.7.6/x64/ssl/cert.pem
  Cert Dir    C:/hostedtoolcache/windows/Ruby/2.7.6/x64/ssl/certs
Tools         
  Git         2.37.3.windows.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed


## Bundler Build Metadata


Built At          2022-10-05
Git SHA           250d9d4[85](https://github.com/metanorma/mnconvert/actions/runs/3191943380/jobs/5208847647#step:16:86)d
Released Version  true


## Gemfile

### Gemfile

ruby
source "https://rubygems.org"

gem "metanorma-cli"


### Gemfile.lock


<No D:/a/mnconvert/mnconvert/Gemfile.lock found>


--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=undefined+method+%60full_name%27+for+nil+NilClass&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.
make: *** [Makefile:[113](https://github.com/metanorma/mnconvert/actions/runs/3191943380/jobs/5208847647#step:16:114): bundle] Error 1
```

**Comment by Intelligent2013** [comment]
The issues `NoMethodError: undefined method `full_name' for nil:NilClass` raised 2-3 days ago already in https://github.com/rubygems/rubygems/issues?q=is%3Aopen+is%3Aissue+label%3ABundler

`bundler` package downgraded to `2.3.22` temporarily.

**Comment by Intelligent2013** [comment]
`nokogiri` installed successfully, but later `bundler 2.3.23` installed and issue occurs for `expressir` again:
```
bundle
...
Fetching nokogiri 1.13.8
Installing nokogiri 1.13.8 with native extensions
...
Using bundler 2.3.23
...
Fetching expressir 1.2.7
Installing expressir 1.2.7 with native extensions
--- ERROR REPORT TEMPLATE -------------------------------------------------------

NoMethodError: undefined method `full_name' for nil:NilClass
  C:/hostedtoolcache/windows/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/installer/parallel_installer.rb:124:in `block (2 levels) in check_for_unmet_dependencies'
```

Looks like `bundler` `2.3.23` cached somewhere (may be in `Gemfile.lock`...).

**Comment by Intelligent2013** [comment]
Done. The solution is:
```
gem install bundler:2.3.22 metanorma-cli
bundle _2.3.22_ update
```
