### ISSUE TITLE
metanorma crashes for adoc BS 7273-4

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mnconvert#37]
Source document: https://github.com/metanorma/mn-samples-bsi/tree/master/sources.mnconvert/bs-codes-of-practice/bs-7273-4-2015-A1-2021

`bundle exec metanorma -t bsi -x presentation sources.mnconvert/30422111/document.adoc`

```
...
1: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-bsi-1.8.4/lib/relaton_bsi/scrapper.rb:24:in `parse_page'
C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/relaton-bsi-1.8.4/lib/relaton_bsi/scrapper.rb:79:in `fetch_editorialgroup': undefined method `text' for nil:NilClass (NoMethodError)
```

**Comment by Intelligent2013** [comment]
This error occurs due this line in `02-normrefs.adoc`:
```adoc
* [[[BS_EN_61386-1,BS EN 61386-1]]], _Conduit systems for cable management – Part 1: General requirements_
```

After commenting, xml creates successfully.

A month ago, xml was created successfully also with this line and bibitem looks ok:
```xml
<bibitem id="BS_EN_61386-1">
	<formattedref format="application/x-isodoc+xml">
		<em>Conduit systems for cable management &#8211; Part 1: General requirements</em>
	</formattedref>
	<docidentifier type="metanorma">[N5]</docidentifier>
	<docidentifier>BS EN 61386-1</docidentifier>
	<docnumber>61386-1</docnumber>
</bibitem>
```

it's too hard puzzle for me...

**Comment by Intelligent2013** [comment]
Simple test application:
```ruby
require 'relaton_bsi'

hit_collection = RelatonBsi::BsiBibliography.search("BS EN 61386-1")
item = hit_collection[1].fetch
print item
print "\n"
print item.to_xml
```
returns xml without any error:
```xml
#<RelatonBsi::BsiBibliographicItem:0x0000000006f4e358>
<bibitem id="BSEN61386-1-2008+A1-2019" type="standard">
  <fetched>2021-07-24</fetched>
  <title type="title-main" format="text/plain" language="en" script="Latn">Conduit systems for cable management. General requirements</title>
  <title type="main" format="text/plain" language="en" script="Latn">Conduit systems for cable management. General requirements</title>
  <title type="title-main" format="text/plain" language="fr" script="Latn">Systèmes de conduits pour la gestion du câblage Exigences générales</title>
  <title type="main" format="text/plain" language="fr" script="Latn">Systèmes de conduits pour la gestion du câblage Exigences générales</title>
  <title type="title-main" format="text/plain" language="de" script="Latn">Elektroinstallationsrohrsysteme für elektrische Energie und für Informationen Allgemeine Anforderungen</title>
  <title type="main" format="text/plain" language="de" script="Latn">Elektroinstallationsrohrsysteme für elektrische Energie und für Informationen Allgemeine Anforderungen</title>
  <uri type="src">https://shop.bsigroup.com/ProductDetail?pid=000000000030340237</uri>
  <docidentifier type="BSI">BS EN 61386-1:2008+A1:2019</docidentifier>
  <docidentifier type="ISBN">978 0 580 93973 0</docidentifier>
  <date type="published">
    <on>2020-11-12</on>
  </date>
  <contributor>
    <role type="publisher"/>
    <organization>
      <name>British Standards Institution</name>
      <abbreviation>BSI</abbreviation>
      <uri>https://www.bsigroup.com/</uri>
    </organization>
  </contributor>
  <language>en</language>
  <script>Latn</script>
  <abstract format="text/plain" language="en" script="Latn">Voltage, Electric cable systems, Non-metals, Classification systems, Alternating current, Electrical testing, Electromagnetic compatibility, Insulated cables, Metals, Communication cables, Electrical insulation, Marking, Electrical installations, Instructions for use, Electric conduits, Composite materials, Direct current, Fire risks, Insulated wires, Thermal testing, Electrical components, Mechanical testing, Dimensions, Electrical insulating materials </abstract>
  <status>
    <stage>Current</stage>
  </status>
  <copyright>
    <from>2020</from>
    <owner>
      <organization>
        <name>British Standards Institution</name>
        <abbreviation>BSI</abbreviation>
        <uri>https://www.bsigroup.com/</uri>
      </organization>
    </owner>
  </copyright>
  <relation type="complements">
    <bibitem type="standard">
      <formattedref format="text/plain" language="en" script="Latn">BS EN 61386-1:2004</formattedref>
      <uri type="src">https://shop.bsigroup.com/ProductDetail/?pid=000000000030103264</uri>
    </bibitem>
  </relation>
  <place>London</place>
</bibitem>
````

**Comment by Intelligent2013** [comment]
Ticket created for relaton-bsi.
There isn't issue in mnconvert. Closing.
