### ISSUE TITLE
Build failed: undefined method `on' for nil:NilClass

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mnconvert#380]
From https://github.com/metanorma/mnconvert/actions/runs/4318386602/jobs/7536617942:
```
Transforming...
Validate XML against XSD NISO-STS-interchange-1-MathML3-XSD/NISO-STS-interchange-1-mathml3.xsd...
/home/runner/work/mnconvert/mnconvert/documents/iso-rice-en.cd.sts.xml is valid.
End!
cd tests/iso-8601-1 && metanorma site generate --agree-to-terms
[info]: Compiling /home/runner/work/mnconvert/mnconvert/tests/iso-8601-1/sources/iso-tc154-8601-1-en.adoc ...
[relaton] International Astronomical Union Resolution B1.9 (2000) does not have a recognised prefix
[relaton-iso] ("ISO/IEC 646") Fetching from ISO...
[relaton-bipm] ("BIPM Recommendation CCTF 3 (2017)") fetching...
[relaton-itu] ("ITU-R TF.460-6") fetching...
[relaton-iso] ("ISO 8601-2:20[19](https://github.com/metanorma/mnconvert/actions/runs/4318386602/jobs/7536617942#step:17:20)") Fetching from ISO...
[relaton-itu] ("ITU-R TF.460-6") found ITU-R TF.460-6
[relaton-bipm] ("BIPM Recommendation CCTF 3 ([20](https://github.com/metanorma/mnconvert/actions/runs/4318386602/jobs/7536617942#step:17:21)17)") not found.
[relaton-iso] ("ISO 8601-2:2019") Found exact match.
[relaton-iso] ("ISO/IEC 646") Found ("ISO/IEC 646:1991").
[relaton] International Astronomical Union Resolution B1.9 (2000) does not have a recognised prefix
[relaton-iec] ("IEC 60050-113") fetching...
[relaton-iec] ("IEC 60050-113") found IEC 60050-113:2011
Fatal Error: undefined method `on' for nil:NilClass
/opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-iev-1.1.5/lib/relaton_iev.rb:56:in `refs_iev2iec60050part1': undefined method `on' for nil:NilClass (NoMethodError)
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-iev-1.1.5/lib/relaton_iev.rb:46:in `block in refs_iev2iec60050part'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-iev-1.1.5/lib/relaton_iev.rb:44:in `each'
	from /opt/hostedtoolcache/Ruby/2.7.7/x64/lib/ruby/gems/2.7.0/gems/relaton-iev-1.1.5/lib/relaton_iev.rb:44:in `refs_iev2iec60050part'
```

**Comment by Intelligent2013** [comment]
On hold.

**Comment by Intelligent2013** [comment]
No more error.
