### ISSUE TITLE
NISO STS generation error: Invalid content was found starting with element 'formatted-initials'

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mnconvert#405]
Source issue: https://github.com/metanorma/iso-iec-jseg-15/issues/1

> Input: XML (iso-iec-jseg-15/_site/documents/vocabulary/document.presentation.xml)
Output: XML (iso-iec-jseg-15/_site/documents/vocabulary/document.sts.xml), format NISO STS
>
> Transforming...
Validate XML against XSD NISO-STS-interchange-1-MathML3-XSD/NISO-STS-interchange-1-mathml3.xsd...
iso-iec-jseg-15/_site/documents/vocabulary/document.sts.xml is NOT valid reason:
[ERROR] org.xml.sax.SAXParseException; lineNumber: 929; columnNumber: 21; cvc-complex-type.2.4.a: Invalid content was found starting with element 'formatted-initials'. One of '{given-names, prefix, suffix}' is expected.
[ERROR] org.xml.sax.SAXParseException; lineNumber: 941; columnNumber: 21; cvc-complex-type.2.4.a: Invalid content was found starting with element 'formatted-initials'. One of '{given-names, prefix, suffix}' is expected.
[ERROR] org.xml.sax.SAXParseException; lineNumber: 945; columnNumber: 21; cvc-complex-type.2.4.a: Invalid content was found starting with element 'formatted-initials'. One of '{given-names, prefix, suffix}' is expected.
[ERROR] org.xml.sax.SAXParseException; lineNumber: 949; columnNumber: 21; cvc-complex-type.2.4.a: Invalid content was found starting with element 'formatted-initials'. One of '{given-names, prefix, suffix}' is expected.
[ERROR] org.xml.sax.SAXParseException; lineNumber: 957; columnNumber: 26; cvc-complex-type.2.4.a: Invalid content was found starting with element 'title'. One of '{break, bold, fixed-case, italic, monospace, num, overline, roman, sans-serif, sc, strike, underline, ruby, alternatives, inline-graphic, private-char, chem-struct, inline-formula, label, abbrev, index-term, index-term-range-end, milestone-end, milestone-start, named-content, styled-content, annotation, article-title, chapter-title, collab, collab-alternatives, comment, conf-acronym, conf-date, conf-loc, conf-name, conf-sponsor, data-title, date, date-in-citation, day, edition, email, elocation-id, etal, ext-link, fpage, gov, institution, institution-wrap, isbn, issn, issn-l, issue, issue-id, issue-part, issue-title, lpage, month, name, name-alternatives, object-id, page-range, part-title, patent, person-group, pub-id, publisher-loc, publisher-name, role, season, series, size, source, std, string-name, supplement, trans-source, trans-title, uri, version, volume, volume-id, volume-series, year, fn, target, "urn:iso:std:iso:30042:ed-1":entailedTerm, xref, sub, sup}' is expected.
[ERROR] org.xml.sax.SAXParseException; lineNumber: 962; columnNumber: 15; cvc-complex-type.2.4.a: Invalid content was found starting with element 'completename'. One of '{surname, given-names}' is expected.
>
> gems/mnconvert-1.58.0/lib/mnconvert.rb:46:in `convert'
bundler/gems/metanorma-iso-c0208f3e75f2/lib/isodoc/iso/sts_convert.rb:27:in `convert'
bundler/gems/metanorma-iso-c0208f3e75f2/lib/metanorma/iso/processor.rb:63:in `output'
gems/metanorma-1.7.1/lib/metanorma/compile.rb:161:in `process_output_threaded'
gems/metanorma-1.7.1/lib/metanorma/compile.rb:153:in `block in process_exts1'
gems/metanorma-1.7.1/lib/metanorma/worker_pool.rb:11:in `block (4 levels) in initialize'
gems/metanorma-1.7.1/lib/metanorma/worker_pool.rb:9:in `loop'
gems/metanorma-1.7.1/lib/metanorma/worker_pool.rb:9:in `block (3 levels) in initialize'
gems/metanorma-1.7.1/lib/metanorma/worker_pool.rb:8:in `catch'
gems/metanorma-1.7.1/lib/metanorma/worker_pool.rb:8:in `block (2 levels) in initialize'

**Comment by Intelligent2013** [comment]
The issue occurs due the new element `formatted-initials`:
```xml
                <person-group person-group-type="author">
                    <name>
                        <surname>Rosenberg</surname>
                        <formatted-initials>L.</formatted-initials>
                    </name>
                </person-group>
```
Need convert to `<given-names>` (https://www.niso-sts.org/TagLibrary/niso-sts-TL-1-2-html/element/given-names.html).

**Comment by Intelligent2013** [comment]
The issue
```
[ERROR] org.xml.sax.SAXParseException; lineNumber: 957; columnNumber: 26; cvc-complex-type.2.4.a: Invalid content was found starting with element 'title'. ...
```
occurs in the conversion of
```xml
<bibitem id="snow_crash" schema-version="v1.2.8">
		<title type="main" format="text/plain">Snow crash</title>
```
into
```
<ref id="biblref_20">
	<label>[20]</label>
	<mixed-citation>, <title>Snow crash</title>
```
If `bibitem` doesn't contain the attribute `@type`, then `title` should be converted to `italic`.


The issue
```
[ERROR] org.xml.sax.SAXParseException; lineNumber: 962; columnNumber: 15; cvc-complex-type.2.4.a: Invalid content was found starting with element 'completename'...
```
occurs due the new element `completename` in the source MN XML:
```xml
<person>
	<name>
		<completename>Neal Stephenson</completename>
	</name>
</person>
```
NISO STS XML:
```xml
<person-group person-group-type="author">
	<name>
		<completename>Neal Stephenson</completename>
	</name>
</person-group>
```
Need convert to `string-name` (Name of Person (Unstructured), https://www.niso-sts.org/TagLibrary/niso-sts-TL-1-2-html/element/string-name.html):
```xml
<person-group person-group-type="author">
	<string-name>Neal Stephenson</string-name>
</person-group>
```

**Comment by Intelligent2013** [comment]
Done. https://github.com/metanorma/mnconvert/releases/tag/v1.59.0
