### ISSUE TITLE
Support webp image format in PDF generation

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mnconvert#409]
From @Intelligent2013 :
* https://github.com/metanorma/mn-samples-plateau/issues/7
* https://github.com/metanorma/metanorma-plateau/issues/2

`mn2pdf` reports the errors:
```
Image not available. URI: data:image/webp;base64,UklGRmhLAABXRUJQVlA4WAoAAAAAAAAA... (See position 22:25922)
org.apache.xmlgraphics.image.loader.ImageException: The file format is not supported. No ImagePreloader found for data:image/webp;base64,UklGRmhLAABXRUJ...
	at org.apache.xmlgraphics.image.loader.ImageManager.preloadImage(ImageManager.java:181)
	at org.apache.xmlgraphics.image.loader.cache.ImageCache.needImageInfo(ImageCache.java:127)
	at org.apache.xmlgraphics.image.loader.ImageManager.getImageInfo(ImageManager.java:123)
	at org.apache.fop.fo.flow.ExternalGraphic.bind(ExternalGraphic.java:81)
```

The .webp images in https://github.com/metanorma/mn-samples-plateau/tree/main/sources/001-v3/images should be converted to .svg or .png images.

**Comment by ronaldtse** [comment]
I've done some research but seems that Apache FOP does not yet support (and no plans to support) the WEBP image format.

We'll have to check in again later.
