### ISSUE TITLE
Crash in ISO NISO STS XML generation in ISO 19135

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mnconvert#410]
https://github.com/metanorma/iso-19135

```sh
$ bundle exec metanorma site generate
...
Input: XML (~/src/mn/iso-19135/_site/documents/iso-19135-2021/document.presentation.xml)
Output: XML (~/src/mn/iso-19135/_site/documents/iso-19135-2021/document.sts.xml), format NISO STS

Transforming...
Validate XML against XSD NISO-STS-interchange-1-MathML3-XSD/NISO-STS-interchange-1-mathml3.xsd...
~/src/mn/iso-19135/_site/documents/iso-19135-2021/document.sts.xml is NOT valid reason:
[ERROR] org.xml.sax.SAXParseException; lineNumber: 12407; columnNumber: 61; cvc-complex-type.3.2.2: Attribute 'class' is not allowed to appear in element 'table'.
[ERROR] org.xml.sax.SAXParseException; lineNumber: 12407; columnNumber: 61; cvc-complex-type.3.2.2: Attribute 'presentation' is not allowed to appear in element 'table'.
[ERROR] org.xml.sax.SAXParseException; lineNumber: 12407; columnNumber: 61; cvc-complex-type.3.2.2: Attribute 'type' is not allowed to appear in element 'table'.

~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/mnconvert-1.59.0/lib/mnconvert.rb:46:in `convert'
~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/metanorma-iso-2.7.10/lib/isodoc/iso/sts_convert.rb:27:in `convert'
~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/metanorma-iso-2.7.10/lib/metanorma/iso/processor.rb:63:in `output'
~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/metanorma-2.0.1/lib/metanorma/compile/compile.rb:175:in `process_output_threaded'
~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/metanorma-2.0.1/lib/metanorma/compile/compile.rb:167:in `block in process_exts1'
~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/metanorma-2.0.1/lib/metanorma/util/worker_pool.rb:21:in `block (3 levels) in init_thread'
<internal:kernel>:187:in `loop'
~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/metanorma-2.0.1/lib/metanorma/util/worker_pool.rb:19:in `block (2 levels) in init_thread'
~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/metanorma-2.0.1/lib/metanorma/util/worker_pool.rb:18:in `catch'
~/.asdf/installs/ruby/3.3.2/lib/ruby/gems/3.3.0/gems/metanorma-2.0.1/lib/metanorma/util/worker_pool.rb:18:in `block in init_thread'
```

**Comment by Intelligent2013** [comment]
Issue fixed.
But issue occurs in bundler:
```
Fetching stringio 3.1.1
Installing stringio 3.1.1 with native extensions
The installation path is insecure. Bundler cannot continue.
/opt/hostedtoolcache/Ruby/3.1.6/x64/lib/ruby/gems/3.1.0/gems is world-writable
(without sticky bit).
Bundler cannot safely replace gems in world-writeable directories due to
potential vulnerabilities.
Please change the permissions of this directory or choose a different install
path.
```

In investigating...

**Comment by Intelligent2013** [comment]
Fixed in https://github.com/metanorma/mnconvert/releases/tag/v1.61.0.
