### ISSUE TITLE
Update XSLTs for new Presentation XML format

### ISSUE THREAD

**Issue by Intelligent2013** [metanorma/mnconvert#418]
As titled.

Source issues:
- https://github.com/metanorma/isodoc/issues/610,
- [x] https://github.com/metanorma/isodoc/issues/607, 
- [x] https://github.com/metanorma/mn-native-pdf/issues/770.
- [x] https://github.com/metanorma/isodoc/issues/632
- [x] https://github.com/metanorma/isodoc/issues/633
- [x] https://github.com/metanorma/mn-requirements/issues/37
- [x] https://github.com/metanorma/metanorma/issues/440
- [x] https://github.com/metanorma/isodoc/issues/645
- [x] https://github.com/metanorma/isodoc/issues/646
- [x] https://github.com/metanorma/isodoc/issues/649
- [x] https://github.com/metanorma/isodoc/issues/651
- [x] https://github.com/metanorma/isodoc/issues/652
- [x] https://github.com/metanorma/isodoc/issues/655
- [x] https://github.com/metanorma/isodoc/issues/658
- [x] https://github.com/metanorma/isodoc/issues/670
- [x] https://github.com/metanorma/isodoc/issues/675
- [x] https://github.com/metanorma/isodoc/issues/687
- [x] https://github.com/metanorma/metanorma-standoc/issues/1053

**Comment by opoudjis** [comment]
With the new Presentation XML refactor coming out of https://github.com/metanorma/isodoc/issues/617, metanorma-iso now breaks on trying to test for STS conversion. Should I remove that integration testing, or keep it?

**Comment by Intelligent2013** [comment]
> With the new Presentation XML refactor coming out of [metanorma/isodoc#617](https://github.com/metanorma/isodoc/issues/617), metanorma-iso now breaks on trying to test for STS conversion. Should I remove that integration testing, or keep it?

Please keep it, I'm going to update `mnconvert` for the test passing as minimum. If the integration testing is stopping the release, then remove it temporarely.

**Comment by Intelligent2013** [comment]
Currently, `mnconvert` allows to convert ISO/NISO STS XML to Metanorma XML.
Metanorma XML is constantly changing. The changes in the Metanorma XML should be reflected in the STS XML to Metanorma XML conversion rules in the `mnconvert`. Errors and discrepancies between 'true' Metanorma XML and converted may occur, because the conversion between STS XML and Metanorma XML is not just 'tag-to-tag' conversion, there is complex logic often. The constantly updating of conversion isn't complex task, but it takes a time.

Does the generation STS XML to MN XML directly make sense? In which scenarios it can be used?

Metanorma XML can be generated in this workflow:
- ISO/NISO STS XML to Metanorma Adoc
- generate Metanorma XML from Adoc

Could it be to drop the ISO/NISO STS to Metanorma XML conversion in `mnconvert`?

@ronaldtse @opoudjis any thoughts on this?

**Comment by Intelligent2013** [comment]
> With the new Presentation XML refactor coming out of [metanorma/isodoc#617](https://github.com/metanorma/isodoc/issues/617), metanorma-iso now breaks on trying to test for STS conversion. Should I remove that integration testing, or keep it?

@opoudjis `mnconvert` updated (https://github.com/metanorma/mnconvert/releases/tag/v1.65.0).

**Comment by opoudjis** [comment]
mnconvert is updated to 1.65.0 on my side, but STS generation is still crashing when running rspec in metanorma-iso:

````
  1) Metanorma::Iso::Processor generates STS from Metanorma XML
     Failure/Error:
       MnConvert.convert(in_fname,
                         { input_format: MnConvert::InputFormat::MN,
                           output_file: out_fname || "#{filename}.#{@suffix}" })
     
     RuntimeError:
       Input: XML (test.xml)
       Output: XML (test.sts.xml), format NISO STS
     
       Transforming...
       Validate XML against XSD NISO-STS-interchange-1-MathML3-XSD/NISO-STS-interchange-1-mathml3.xsd...
       /Users/nickn/Documents/Arbeit/upwork/ribose/metanorma-iso/test.sts.xml is NOT valid reason:
       [ERROR] org.xml.sax.SAXParseException; lineNumber: 51; columnNumber: 22; cvc-complex-type.2.4.a: Invalid content was found starting with element 'fmt-title'. One of '{title, address, alternatives, array, boxed-text, chem-struct-wrap, code, fig, fig-group, graphic, media, non-normative-note, normative-note, non-normative-example, normative-example, notes-group, preformat, supplementary-material, table-wrap, table-wrap-group, disp-formula, disp-formula-group, editing-instruction, def-list, list, tex-math, "http://www.w3.org/1998/Math/MathML":math, p, related-article, related-object, disp-quote, speech, statement, verse-group, fn-group, glossary, ref-list, sec, term-sec}' is expected.
       [ERROR] org.xml.sax.SAXParseException; lineNumber: 56; columnNumber: 11; cvc-complex-type.2.4.a: Invalid content was found starting with element 'fmt-name'. One of '{"urn:iso:std:iso:30042:ed-1":crossReference, "urn:iso:std:iso:30042:ed-1":definition, "urn:iso:std:iso:30042:ed-1":example, "urn:iso:std:iso:30042:ed-1":externalCrossReference, "urn:iso:std:iso:30042:ed-1":note, "urn:iso:std:iso:30042:ed-1":see, "urn:iso:std:iso:30042:ed-1":source, "urn:iso:std:iso:30042:ed-1":subjectField, "urn:iso:std:iso:30042:ed-1":xGraphic, "urn:iso:std:iso:30042:ed-1":xMathML, "urn:iso:std:iso:30042:ed-1":xSource, "urn:iso:std:iso:30042:ed-1":tig}' is expected.
     # ./lib/isodoc/iso/sts_convert.rb:27:in 'IsoDoc::Iso::StsConvert#convert'
     # ./lib/metanorma/iso/processor.rb:62:in 'Metanorma::Iso::Processor#output'
     # ./spec/metanorma/processor_spec.rb:166:in 'block (2 levels) in <top (required)>'
````

**Comment by Intelligent2013** [comment]
Confirmed. I'll fix.

**Comment by Intelligent2013** [comment]
@opoudjis `mnconvert` updated (https://github.com/metanorma/mnconvert/releases/tag/v1.66.0).

**Comment by opoudjis** [comment]
> Currently, `mnconvert` allows to convert ISO/NISO STS XML to Metanorma XML. Metanorma XML is constantly changing. The changes in the Metanorma XML should be reflected in the STS XML to Metanorma XML conversion rules in the `mnconvert`. Errors and discrepancies between 'true' Metanorma XML and converted may occur, because the conversion between STS XML and Metanorma XML is not just 'tag-to-tag' conversion, there is complex logic often. The constantly updating of conversion isn't complex task, but it takes a time.
> 
> Does the generation STS XML to MN XML directly make sense? In which scenarios it can be used?
> 
> Metanorma XML can be generated in this workflow:
> 
> * ISO/NISO STS XML to Metanorma Adoc
> * generate Metanorma XML from Adoc
> 
> Could it be to drop the ISO/NISO STS to Metanorma XML conversion in `mnconvert`?
> 
> @ronaldtse @opoudjis any thoughts on this?

I'm sorry to say I don't have the business context for STS XML > MN XML conversion, but I agree with you that using Asciidoc as an intermediary representation makes much more sense, and I've argued for it for years in comparable contexts, for the same reason you've given: the XML may be more expressive and more formal, but it is also volatile and will remain so. The Asciidoc is simply more stable.

**Comment by ronaldtse** [comment]
@Intelligent2013 yes indeed. We can drop the STS to MN XML conversion. It's more important that we focus on what users need, which is in this use case, the ability to re-edit and re-publish STS XML.

**Comment by opoudjis** [comment]
The ST4S apparently needs to be updated for Presentation XML for terms as well, the conversion is breaking in metanorma-iso

````
       Transforming...
       Validate XML against XSD NISO-STS-interchange-1-MathML3-XSD/NISO-STS-interchange-1-mathml3.xsd...
       /Users/nickn/Documents/Arbeit/upwork/ribose/metanorma-iso/test.sts.xml is NOT valid reason:
       [ERROR] org.xml.sax.SAXParseException; lineNumber: 57; columnNumber: 16; cvc-complex-type.2.4.a: Invalid content was found starting with element 'fmt-preferred'. One of '{"urn:iso:std:iso:30042:ed-1":crossReference, "urn:iso:std:iso:30042:ed-1":definition, "urn:iso:std:iso:30042:ed-1":example, "urn:iso:std:iso:30042:ed-1":externalCrossReference, "urn:iso:std:iso:30042:ed-1":note, "urn:iso:std:iso:30042:ed-1":see, "urn:iso:std:iso:30042:ed-1":source, "urn:iso:std:iso:30042:ed-1":subjectField, "urn:iso:std:iso:30042:ed-1":xGraphic, "urn:iso:std:iso:30042:ed-1":xMathML, "urn:iso:std:iso:30042:ed-1":xSource, "urn:iso:std:iso:30042:ed-1":tig}' is expected.
````

in spec/metanorma/processor_spec.rb, line 161

**Comment by Intelligent2013** [comment]
A week ago I've tested on ISO Rice document and the STS output XML was ok.
Ok, I'll check the XML from gem.

**Comment by Intelligent2013** [comment]
> The ST4S apparently needs to be updated for Presentation XML for terms as well, the conversion is breaking in metanorma-iso

Issue fixed in https://github.com/metanorma/mnconvert/releases/tag/v1.67.0.

**Comment by Intelligent2013** [comment]
Source XML - new Presentation XML format without Semantic part
Output XML - NISO STS XML.

Validation issues:
```
[ERROR] org.xml.sax.SAXParseException; lineNumber: 48; columnNumber: 25; cvc-complex-type.2.4.a: Invalid content was found starting with element 'source-highlighter-css'. One of '{custom-meta-group}' is expected.
[ERROR] org.xml.sax.SAXParseException; lineNumber: 50; columnNumber: 12; cvc-complex-type.2.3: Element 'nat-meta' cannot have character [children], because the type's content type is element-only.
[ERROR] org.xml.sax.SAXParseException; lineNumber: 68; columnNumber: 7; cvc-complex-type.2.3: Element 'sec' cannot have character [children], because the type's content type is element-only.
[ERROR] org.xml.sax.SAXParseException; lineNumber: 69; columnNumber: 4; cvc-complex-type.2.4.a: Invalid content was found starting with element 'p'. One of '{sec, term-sec, fn-group, glossary, ref-list, non-normative-note, normative-note, non-normative-example, normative-example, notes-group}' is expected.
[ERROR] org.xml.sax.SAXParseException; lineNumber: 885; columnNumber: 41; cvc-complex-type.2.4.a: Invalid content was found starting with element 'p'. One of '{sec, term-sec, sub-part, "http://www.w3.org/2001/XInclude":include, sig-block}' is expected.
[ERROR] org.xml.sax.SAXParseException; lineNumber: 885; columnNumber: 41; cvc-complex-type.3.2.2: Attribute 'class' is not allowed to appear in element 'p'.
[ERROR] org.xml.sax.SAXParseException; lineNumber: 885; columnNumber: 41; cvc-complex-type.3.2.2: Attribute 'displayorder' is not allowed to appear in element 'p'.
[ERROR] org.xml.sax.SAXParseException; lineNumber: 888; columnNumber: 41; cvc-complex-type.3.2.2: Attribute 'class' is not allowed to appear in element 'p'.
[ERROR] org.xml.sax.SAXParseException; lineNumber: 888; columnNumber: 41; cvc-complex-type.3.2.2: Attribute 'displayorder' is not allowed to appear in element 'p'.
[ERROR] org.xml.sax.SAXParseException; lineNumber: 2830; columnNumber: 22; cvc-complex-type.3.2.2: Attribute 'autonum' is not allowed to appear in element 'table'.
[ERROR] org.xml.sax.SAXParseException; lineNumber: 3573; columnNumber: 109; cvc-complex-type.2.4.a: Invalid content was found starting with element 'biblio-tag'. One of '{break, bold, fixed-case, italic, monospace, num, overline, roman, sans-serif, sc, strike, underline, ruby, alternatives, inline-graphic, private-char, chem-struct, inline-formula, label, abbrev, index-term, index-term-range-end, milestone-end, milestone-start, named-content, styled-content, annotation, article-title, chapter-title, collab, collab-alternatives, comment, conf-acronym, conf-date, conf-loc, conf-name, conf-sponsor, data-title, date, date-in-citation, day, edition, email, elocation-id, etal, ext-link, fpage, gov, institution, institution-wrap, isbn, issn, issn-l, issue, issue-id, issue-part, issue-title, lpage, month, name, name-alternatives, object-id, page-range, part-title, patent, person-group, pub-id, publisher-loc, publisher-name, role, season, series, size, source, std, string-name, supplement, trans-source, trans-title, uri, version, volume, volume-id, volume-series, year, fn, target, "urn:iso:std:iso:30042:ed-1":entailedTerm, xref, sub, sup}' is expected.
[ERROR] org.xml.sax.SAXParseException; lineNumber: 3577; columnNumber: 130; cvc-complex-type.2.4.a: Invalid content was found starting with element 'biblio-tag'. One of '{break, bold, fixed-case, italic, monospace, num, overline, roman, sans-serif, sc, strike, underline, ruby, alternatives, inline-graphic, private-char, chem-struct, inline-formula, label, abbrev, index-term, index-term-range-end, milestone-end, milestone-start, named-content, styled-content, annotation, article-title, chapter-title, collab, collab-alternatives, comment, conf-acronym, conf-date, conf-loc, conf-name, conf-sponsor, data-title, date, date-in-citation, day, edition, email, elocation-id, etal, ext-link, fpage, gov, institution, institution-wrap, isbn, issn, issn-l, issue, issue-id, issue-part, issue-title, lpage, month, name, name-alternatives, object-id, page-range, part-title, patent, person-group, pub-id, publisher-loc, publisher-name, role, season, series, size, source, std, string-name, supplement, trans-source, trans-title, uri, version, volume, volume-id, volume-series, year, fn, target, "urn:iso:std:iso:30042:ed-1":entailedTerm, xref, sub, sup}' is expected.

```

**Comment by Intelligent2013** [comment]
In the output NISO XMLfound the missing tags for the terms references.

For instance, in the source BSI document (https://github.com/metanorma/mn-samples-bsi/tree/main/sources/bs-202000), in `00-introduction.adoc` there are references to the terms `process` and `standard`:
```
SM is a through-life {{process}} that enables the drafting, development and maintenance of {{standard,standards}}. It promotes the intelligent selection and implementation of {{standard,standards}}, policy, {{process,processes}} and tools, and delivers:
```
The Presentation XML contains the plain text only:
```
<p id="_34c2a109-0b03-f25c-efc8-7ba7fd222919">SM is a through-life process that enables the drafting, development and maintenance of standards. It promotes the intelligent selection and implementation of standards, policy, processes and tools, and delivers:</p>
```


Previously, the Semantic part (which used as 'base' for the conversion) contained this markup:
```xml
<semantic__p id="semantic___34c2a109-0b03-f25c-efc8-7ba7fd222919">SM is a through-life <semantic__concept><semantic__refterm>process</semantic__refterm><semantic__renderterm>process</semantic__renderterm><semantic__xref target="semantic__term-process"/></semantic__concept> that enables the drafting, development and maintenance of <semantic__concept><semantic__refterm>standard</semantic__refterm><semantic__renderterm>standards</semantic__renderterm><semantic__xref target="semantic__term-standard"/></semantic__concept>. It promotes the intelligent selection and implementation of <semantic__concept><semantic__refterm>standard</semantic__refterm><semantic__renderterm>standards</semantic__renderterm><semantic__xref target="semantic__term-standard"/></semantic__concept>, policy, <semantic__concept><semantic__refterm>process</semantic__refterm><semantic__renderterm>processes</semantic__renderterm><semantic__xref target="semantic__term-process"/></semantic__concept> and tools, and delivers:</semantic__p>
```

I'll add the issue in the `isodoc` repository.

**Comment by ronaldtse** [comment]
@opoudjis what's the plan for footnotes? Placing them in a unified container per document? Ideally we separate footnote content and applicable locality, in order to allow shared footnotes (and differentiation in locality).

**Comment by Intelligent2013** [comment]
`mnconvert` fails on the processing XML from the repository `mn-samples-iso`:
https://github.com/metanorma/mnconvert/actions/runs/13461620115/job/37618126610?pr=422
because XMLs in old format (`iso-standard` root tag). I'll run the XMLs re-generation.

**Comment by Intelligent2013** [comment]
version `2.9.5` (from Jan, 20):
```
<iso-standard xmlns="https://www.metanorma.org/ns/iso" type="presentation" version="2.9.5" schema-version="v1.4.1">
```
because Metanorma docker updated 30 days ago: https://hub.docker.com/r/metanorma/metanorma.

**Comment by Intelligent2013** [comment]
XSLT updated for old XML to STS XML conversion and validation.
Now, the issue https://github.com/metanorma/metanorma-plugin-lutaml/issues/192 occurs.

**Comment by Intelligent2013** [comment]
Done.
https://github.com/metanorma/mnconvert/releases/tag/v1.69.0

**Comment by Intelligent2013** [comment]
From https://github.com/metanorma/mnconvert/actions/runs/15788946756/job/44511174599?pr=426:
```
Input: XML (documents/iso-tc154-8601-1-en.mn.xml)
...
Error:  org.xml.sax.SAXParseException; lineNumber: 1636; columnNumber: 33; cvc-complex-type.3.2.2: Attribute 'anchor' is not allowed to appear in element 'table'
```
```xml
<table id="calendar-months" anchor="calendar-months" semx-id="_aa391fb2-ea5d-bbfa-bcb2-de9e9c3354aa" autonum="1">
```

**Comment by Intelligent2013** [comment]
```
[ERROR] org.xml.sax.SAXParseException; lineNumber: 1622; columnNumber: 35; cvc-datatype-valid.1.2.1: 'symbol-_:_-_colon_' is not a valid value for 'NCName'.
[ERROR] org.xml.sax.SAXParseException; lineNumber: 1622; columnNumber: 35; cvc-attribute.3: The value 'symbol-_:_-_colon_' of attribute 'id' on element 'def-item' is not valid with respect to its type, 'ID'
```

**Comment by Intelligent2013** [comment]
From https://github.com/metanorma/mnconvert-ruby/actions/runs/15793559641/job/44522676187:
```
RuntimeError:
       Input: XML (/home/runner/work/mnconvert-ruby/mnconvert-ruby/spec/../ieee/samples/_site/documents/p987.6/document.xml)
       Output: XML (/tmp/rspec-20250621-2262-1eajy6/p987.6.xml), format IEEE 

       DocumentBuilderFactory implementation: org.apache.xerces.jaxp.DocumentBuilderFactoryImpl loaded from: file:/home/runner/work/mnconvert-ruby/mnconvert-ruby/bin/mnconvert.jar
       XPathFactory implementation: org.apache.xpath.jaxp.XPathFactoryImpl loaded from: file:/home/runner/work/mnconvert-ruby/mnconvert-ruby/bin/mnconvert.jar
       TransformerFactory implementation: org.apache.xalan.processor.TransformerFactoryImpl loaded from: file:/home/runner/work/mnconvert-ruby/mnconvert-ruby/bin/mnconvert.jar
       SAXParserFactory implementation: org.apache.xerces.jaxp.SAXParserFactoryImpl loaded from: file:/home/runner/work/mnconvert-ruby/mnconvert-ruby/bin/mnconvert.jar
       Transforming...
 ......
       Validate XML against DTD /home/runner/work/mnconvert-ruby/mnconvert-ruby/spec/../ieee/stl/standards-1-7-DTD/standards-1-7-dtd/standards.dtd...
       /tmp/rspec-20250621-2262-1eajy6/p987.6.xml is NOT valid reason:
Error: [ERROR] org.xml.sax.SAXParseException; lineNumber: 2[59](https://github.com/metanorma/mnconvert-ruby/actions/runs/15793559641/job/44522676187#step:9:60); columnNumber: 7; The content of element type "sec" must match "(sec-meta?,editing-instruction*,((label,title?)|title),(address|algorithm|alternatives|array|boxed-text|code|caution|fig|graphic|media|non-normative-note|preformat|supplementary-material|table-wrap|warning|disp-formula|disp-formula-group|editing-instruction|p|def-list|list|tex-math|mml:math|related-article|related-object|disp-quote)*,(sec|participants-sec)*,(ref-list|std-def-list)*)".
Error: [ERROR] org.xml.sax.SAXParseException; lineNumber: 276; columnNumber: 7; The content of element type "sec" must match "(sec-meta?,editing-instruction*,((label,title?)|title),(address|algorithm|alternatives|array|boxed-text|code|caution|fig|graphic|media|non-normative-note|preformat|supplementary-material|table-wrap|warning|disp-formula|disp-formula-group|editing-instruction|p|def-list|list|tex-math|mml:math|related-article|related-object|disp-quote)*,(sec|participants-sec)*,(ref-list|std-def-list)*)".
Error: [ERROR] org.xml.sax.SAXParseException; lineNumber: 310; columnNumber: 7; The content of element type "sec" must match "(sec-meta?,editing-instruction*,((label,title?)|title),(address|algorithm|alternatives|array|boxed-text|code|caution|fig|graphic|media|non-normative-note|preformat|supplementary-material|table-wrap|warning|disp-formula|disp-formula-group|editing-instruction|p|def-list|list|tex-math|mml:math|related-article|related-object|disp-quote)*,(sec|participants-sec)*,(ref-list|std-def-list)*)".
```

**Comment by Intelligent2013** [comment]
Done.
https://github.com/metanorma/mnconvert/releases/tag/v1.72.0
